# TERRAFORM MODULE SCANNER
# Version: 1.0.0
# Date: 2023-10-05
# Author: Neil Grinnall
#
# A GitHub Action for Terraform Modules
# - Runs 'terraform fmt'
# - Runs 'terraform validate'
# - Checks Code using TFLInt
# - Scans for security issues using CHECKOV
# - Creates/updates README.md using Terraform Docs
name: 'Terraform Module Scanner'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'

env:
  SLACK_CHANNEL_ID: 'C060DK2BWQM' # Define the Slack channel ID here

jobs:

### ------------------------------------------ ###
# TERRAFORM FMT & VALIDATE
### ------------------------------------------ ###
# Set up the Terraform environment on the runner machine and
# validate the Terraform code to ensure that it is ready for 
# further deployment or management of infrastructure resources
#
# If the terraform validate command fails, subsequent steps in
# the workflow will not execute.

  terraform-fmt-validate:
    name: 'Terraform FMT & Validate'
    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    
  ## Check out the code to the runner environment where the workflow is running
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        ref: main
  
  ## Pull any changes down to the working directory      
    - name: Pull latest changes
      run: git pull origin main
        
  ## Install Terraform CLI on the runner machine
    - name: Setup Terraform on the runner
      uses: hashicorp/setup-terraform@v2.0.3

# This step is responsible for initializing, formatting, and validating the Terraform code.
# 
# 1. `terraform init -backend=false`: 
#    - Initializes the Terraform working directory.
#    - Downloads the required provider plugins.
#    - The `-backend=false` option disables backend configuration, which means Terraform will use a local backend.
#      This means the Terraform state will be stored on the runner machine where the workflow is executed.
#
# 2. `terraform fmt`: 
#    - Automatically formats the Terraform code to adhere to a canonical format and style.
#
# 3. `terraform validate`: 
#    - Validates the Terraform code's syntax and checks for any errors.
    - name: Terraform init, fmt, & validate
      run: |
        terraform init -backend=false; terraform fmt; terraform validate
        
  ## Commit the results to a sub-folder in the repository
    - name: Commit any changes to this repository
      uses: EndBug/add-and-commit@v9.1.1
      with:
        add: '.'
        author_name: 'GitHub Action - terraform-module-scanner'
        message: 'Resulting from Terraform init, fmt, & validate'    

  ## Push changes to the main branch.
  ## Requires authentication, which is provided through a GITHUB_TOKEN 
  ## environment variable.
    - name: Push changes to main branch
      uses: ad-m/github-push-action@master
      with:
        branch: main
        directory: ./
        github_token: ${{ env.GITHUB_TOKEN }}

### ------------------------------------------ ###
# TFLint
### ------------------------------------------ ###
# Lint Terraform configurations using TFLint
  tflint:
    name: 'TFLint'
    runs-on: ubuntu-latest
    needs: [terraform-fmt-validate]
    
    steps:
    # Check out the code to the runner environment where the workflow is running
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        ref: main
    
    ## Pull any changes down to the working directory      
    - name: Pull latest changes
      run: git pull origin main

    # Caching TFLint plugins to optimize workflow execution time.
    # This action leverages GitHub's caching infrastructure to store and retrieve TFLint plugins.
    # The cache is not stored on the ephemeral runner but in GitHub's centralized cache storage.
    # The key for the cache is constructed using the runner's OS and a hash of the '.tflint.hcl' file.
    # A change in the '.tflint.hcl' file will generate a new cache, ensuring relevant plugins are used.
    - name: Setup TFLint cache
      uses: actions/cache@v3
      with:
        path: ~/.tflint.d/plugins
        key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    # Set up and install the specified version of TFLint
    - name: Install TFLint v0.44.1
      uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: v0.44.1

    # Set up TFLint plugins using the provided configuration file.
    # The '--init' flag initializes the plugins, and the '--config' flag specifies the configuration file path.
    # The tflint.hcl patch is relative to the repository where the action is run
    # The tflint.hcl file can be changed according to what you're linting
    # By default it'll have the azure and aws libraries
    - name: Initialize TFLint Plugins
      run: tflint --init --config ./tflint/tflint.hcl
      env:
        # Provide the GitHub token to allow TFLint to access any required GitHub resources.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Ensure the tflint/ directory exists
    # This is used to save the output as a log file
    - name: Create tflint directory if it doesn't exist
      run: mkdir -p tflint

    # Execute TFLint and store the results in a timestamped file within the 'tflint' directory.
    - name: Execute TFLint and Store Results
    # Uncomment the line below if you want the workflow to continue even if this step encounters an error.
      #continue-on-error: true
  
      run: |
        # Execute TFLint without output redirection to display potential error messages directly in the workflow logs.
        tflint -f compact --config ./tflint/tflint.hcl || true
          
        # Capture the current date and time to create a unique timestamp for the results file.
        TIMESTAMP=$(date "+%Y%m%d-%H%M%S")
        
        # Run TFLint again and redirect its output to a timestamped file in the 'tflint' directory.
        tflint -f compact --config ./tflint/tflint.hcl > tflint/tflint-results-$TIMESTAMP.txt

    # Commit the TFLint results file(s) to the repository.
    # This step uses the 'EndBug/add-and-commit' action to automatically add and commit the generated TFLint results.
    - name: Commit TFLint Results
      uses: EndBug/add-and-commit@v9.1.1
      with:
        # Specify the path pattern to the TFLint results files that need to be added to the commit.
        add: './tflint/tflint-results-*.txt'
        # Define the author name for the commit.
        author_name: 'terraform-module-scanner'
        # Set the commit message.
        message: 'Add TFLint scan results'

### ------------------------------------------ ###
# CHECKOV SECURITY SCAN
### ------------------------------------------ ###
# Run a security scan on the Terraform code using the Checkov tool.
# Commit the results to the repository.

  checkov-security-scan:
    name: 'Checkov Security Scan'
    runs-on: ubuntu-latest
    needs: [terraform-fmt-validate,TFLint]
#    
# Required to access the repository and perform Git operations.
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    
# Check out the code to the runner environment where the workflow is running
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        ref: main
  
# Pull any changes down to the working directory      
    - name: Pull latest changes
      run: |
        git pull origin main

# Ensure the checkov/ directory exists
    - name: Create checkov directory if it doesn't exist
      run: mkdir -p checkov

# Generate the timestamped file path for the Checkov scan results
    - name: Generate Checkov output file path
      run: echo "CHECKOV_OUTPUT_FILE=./checkov/checkov-security-scan-$(date "+%Y%m%d-%H%M%S")" >> $GITHUB_ENV

# Run a security scan on the Terraform code using the Checkov tool.
# Generate a report of security issues that were found.
    - name: Run Checkov Scan
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ./
        framework: terraform
        output_format: cli
        output_file_path: ${{ env.CHECKOV_OUTPUT_FILE }}
        soft_fail: 'true'
        skip_check: 'CKV_TF_1' # Skips failing on using ?ref=0.0.1 instead of commit hash as module source
        compact: 'true'

# Add the Checkov scan report to the repository and commit it with a commit message.
# This action requires authentication, which is provided through GITHUB_TOKEN.
    - name: Commit the results to this repository
      uses: EndBug/add-and-commit@v9.1.1
      with:
        add: './checkov/checkov-security-scan-*.txt'
        author_name: 'Neil Grinnall'
        message: 'Checkov results'

# Push changes to the main branch.
# Requires authentication, which is provided through a GITHUB_TOKEN environment variable.
    - name: Push changes to main branch
      uses: ad-m/github-push-action@master
      with:
        branch: main
        directory: ./
        github_token: ${{ env.GITHUB_TOKEN }}

### ------------------------------------------ ###
# TERRAFORM-DOCS
### ------------------------------------------ ###
# Automatically generate and update documentation for Terraform
# modules in the README.md file, and push the changes back to 
# the pull request branch in GitHub.

  terraform-docs:
    name: 'Terraform Docs'
    runs-on: ubuntu-latest
    needs: checkov-security-scan
    
    steps:
    
  # Check out the code to the runner environment where the workflow is running
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        ref: main
  
  # Pull any changes down to the working directory      
    - name: Pull latest changes
      run: |
        git pull origin main

    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    
    - name: Get latest tag
      id: latesttag
      run: echo ::set-output name=tag::$(git describe --tags $(git rev-list --tags --max-count=1))
    
    - name: Update README.md
      run: |
       sed -i "s/\(https:\/\/img.shields.io\/badge\/Tag\)-.*-blue/\1-${{ steps.latesttag.outputs.tag }}-blue/" README.md

    # Update README.md title with repository name and latest tag
    - name: Update README.md title
      run: |
        REPO_NAME=$(basename `git rev-parse --show-toplevel`)
        sed -i "s/\[REPO_NAME\]/$REPO_NAME/" README.md

  # Render terraform docs inside the README.md and push changes back to PR branch
    - name: Create or update readme.md file
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        config-file: ./terraform-docs/terraform-docs.yml
        git-push: "true"

### ------------------------------------------ ###
# NOTIFY SLACK ON ANY FAILURE
### ------------------------------------------ ###

  notify-slack-on-failure:
    name: 'Notify Slack on Any Failure'
    runs-on: ubuntu-latest
    if: failure() # This ensures the job runs only if any previous job fails
    needs: [terraform-fmt-validate, tflint, checkov-security-scan, terraform-docs] # List all jobs here
    steps:
    - name: Notify Slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: ${{ env.SLACK_CHANNEL_ID }}
        payload: |
          {
            "text": ":boom:Error in workflow: ${{ github.workflow }} \n\n \n\nRepository::file_folder:${{ github.repository }} \n\n:clipboard:Check the GitHub Action logs for detailed results.",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":boom:Error in workflow: ${{ github.workflow }} \n\n \n\nRepository::file_folder:${{ github.repository }} \n\n:clipboard:Check the GitHub Action logs for detailed results."
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": ":github: View Action"
                    },
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATIONS_TOKEN }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK